# Generated by Django 4.0.2 on 2022-02-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_programming_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('level', models.CharField(choices=[('associate', 'associate'), ('proffessional', 'proffessional'), ('expert', 'expert')], max_length=20)),
                ('exam_type', models.CharField(choices=[('proiect', 'proiect'), ('teoretic', 'teoretic'), ('practic', 'practic')], max_length=20)),
            ],
        ),
    ]
