# Generated by Django 4.0.2 on 2022-02-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_language_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('level', models.CharField(choices=[('A1', 'A1'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
            ],
        ),
    ]
